require_relative 'core_ext/hash'
require_relative 'core_ext/string'
require_relative 'core_ext/array'
require_relative 'core_ext/boolean/true'
require_relative 'core_ext/boolean/false'
require_relative 'core_ext/kernel'
