# require_relative 'monkey_patches/httparty.rb'
# require_relative 'monkey_patches/dragonfly.rb'
require_relative 'monkey_patches/mounter.rb'
require_relative 'monkey_patches/haml.rb'
# require_relative 'monkey_patches/better_errors.rb'