require_relative 'editable/base'
require_relative 'editable/text'
require_relative 'editable/short_text'
require_relative 'editable/long_text'
require_relative 'editable/file'
require_relative 'editable/control'